module.exports = {
	RECEIVE_TEST_QUERIES: "RECEIVE_TEST_QUERIES",
	RECEIVE_QUERIES: "RECEIVE_QUERIES",
	RECEIVE_USERS: "RECEIVE_USERS",
	RECEIVE_ARTICLES: "RECEIVE_ARTICLES",
	LOGIN_SUBMIT: "LOGIN_SUBMIT",
	SHOW_LOGIN: "SHOW_LOGIN",
	SHOW_APP: "SHOW_APP",
	// Containment Field
	SHOW_MAINSCRN:"SHOW_MAINSCRN",
	SHOW_ARTICLELIST:"SHOW_ARTICLELIST",
	SHOW_INFOONE:"SHOW_INFOONE",
	SHOW_INFOTWO:"SHOW_INFOTWO",
	SHOW_NEWQUERY:"SHOW_NEWQUERY",
	SHOW_DASHBOARD:"SHOW_DASHBOARD",
	SHOW_QUERYLIST:"SHOW_QUERYLIST",
	SHOW_ARTICLESCRN:"SHOW_ARTICLESCRN",
	SHOW_QUERYSCRN:"SHOW_QUERYSCRN",
	SHOW_SETTINGS:"SHOW_SETTINGS"

}
