module.exports = {
	RECEIVE_USERS: "RECEIVE_USERS",
	RECEIVE_DATA: "RECEIVE_DATA",
	RECEIVE_QUERIES: "RECEIVE_QUERIES",
	LOGIN_SUBMIT: "LOGIN_SUBMIT",
	SHOW_LOGIN: "SHOW_LOGIN",
	SHOW_APP: "SHOW_APP",
	SHOW_QUERIES: "SHOW_QUERIES"
}
